### ISSUE TITLE
"checkEpisodeNubmer"키가 생성되지 않는 버그

### ISSUE THREAD

**Issue by whatduckhell** [istandthon7/torrent_web_scraper#37]
install.sh 실행후 생성된 config/setting.json 파일에
`"checkEpisodeNubmer": false`
옵션항목이 이 tvshow 부분에 없어서
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/*****/see_test/./__main__.py", line 139, in <module>
    if not "영화" in category['name'] and mySetting.json["tvshow"]["checkEpisodeNubmer"]:
KeyError: 'checkEpisodeNubmer'
```
오류가 납니다.

**Comment by istandthon7** [comment]
그렇지 않아도 방금 그 부분을 확인하고 있었어요. 
저는 어제 도커 버전으로 했더니 몰랐네요.

**Comment by istandthon7** [comment]
upgrade시 발생할 수 있음
